version: '3.7'

services:

    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
        container_name: elastic
        #command: chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/data
        tty: true
        environment:
            - discovery.type=single-node
            - node.max_local_storage_nodes=20
            - bootstrap.memory_lock=true
            - ES_JAVA_OPTS=-Xms750m -Xmx750m
        volumes:
            - ./data:/usr/share/elasticsearch/data:rw
        ports:
            - 9200:9200
            - 9300:9300
